//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLTDWebPortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ceutltdschedulerEntities : DbContext
    {
        public ceutltdschedulerEntities()
            : base("name=ceutltdschedulerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<user_login_Result> user_login(string entUsername, string entPassword)
        {
            var entUsernameParameter = entUsername != null ?
                new ObjectParameter("EntUsername", entUsername) :
                new ObjectParameter("EntUsername", typeof(string));
    
            var entPasswordParameter = entPassword != null ?
                new ObjectParameter("EntPassword", entPassword) :
                new ObjectParameter("EntPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<user_login_Result>("user_login", entUsernameParameter, entPasswordParameter);
        }
    }
}
